version: '3.8'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    ports:
      - "9696:9696"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/prowlarr:/config
    labels:
      - homepage.group=Indexers
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr
      - homepage.href=http://localhost:9696
      - homepage.widget.type=prowlarr
      - homepage.widget.url=http://prowlarr:9696
      - homepage.widget.key=${PROWLARR_API_KEY}
    restart: unless-stopped
    networks:
      - media_net

  qbittorrent:
    image: ghcr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=${WEBUI_PORT}
    volumes:
      - ./config/qbittorrent:/config
      - ./downloads:/downloads
    labels:
      - homepage.group=Download
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent
      - homepage.href=http://localhost:8080
      - homepage.widget.type=qbittorrent
      - homepage.widget.url=http://qbittorrent:8080
      - homepage.widget.username=${QB_USERNAME}
      - homepage.widget.password=${QB_PASSWORD}
      - homepage.widget.enableLeechProgress=true
    restart: unless-stopped
    networks:
      - media_net

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/sonarr:/config
      - ./downloads:/downloads
      - ./tv:/tv
    labels:
      - homepage.group=Media
      - homepage.name=Sonarr
      - homepage.icon=sonarr
      - homepage.href=http://localhost:8989
      - homepage.widget.type=sonarr
      - homepage.widget.url=http://sonarr:8989
      - homepage.widget.key=${SONARR_API_KEY}
      - homepage.widget.enableQueue=true
    restart: unless-stopped
    networks:
      - media_net

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/radarr:/config
      - ./downloads:/downloads
      - ./movies:/movies
    labels:
      - homepage.group=Media
      - homepage.name=Radarr
      - homepage.icon=radarr
      - homepage.href=http://localhost:7878
      - homepage.widget.type=radarr
      - homepage.widget.url=http://radarr:7878
      - homepage.widget.key=${RADARR_API_KEY}
      - homepage.widget.enableQueue=true
    restart: unless-stopped
    networks:
      - media_net

  jellyseerr:
    image: ghcr.io/fallenbagel/jellyseerr
    container_name: jellyseerr
    ports:
      - "5055:5055"
    environment:
      - LOG_LEVEL=info
      - TZ=${TZ}
    volumes:
      - ./config/jellyseerr:/app/config
    labels:
      - homepage.group=Media
      - homepage.name=Jellyseerr
      - homepage.icon=jellyseerr
      - homepage.href=http://localhost:5055
      - homepage.widget.type=jellyseerr
      - homepage.widget.url=http://jellyseerr:5055
      - homepage.widget.key=${JELLYSEERR_API_KEY}
    restart: unless-stopped
    networks:
      - media_net

  suggestarr:
    image: ciuse99/suggestarr:latest
    container_name: suggestarr
    ports:
      - "5000:5000"
    volumes:
      - ./config/suggestarr:/app/config
    labels:
      - homepage.group=Media
      - homepage.name=Suggestarr
      - homepage.icon=movie
      - homepage.href=http://localhost:5000
    restart: unless-stopped
    networks:
      - media_net

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    environment:
      - TZ=${TZ}
    volumes:
      - ./config/jellyfin:/config
      - ./cache/jellyfin:/cache
      - ./tv:/media/tv
      - ./movies:/media/movies
    labels:
      - homepage.group=Media
      - homepage.name=Jellyfin
      - homepage.icon=jellyfin
      - homepage.href=http://localhost:8096
      - homepage.widget.type=jellyfin
      - homepage.widget.url=http://jellyfin:8096
      - homepage.widget.key=${JELLYFIN_API_KEY}
      - homepage.widget.enableBlocks=true
      - homepage.widget.enableNowPlaying=true
      - homepage.widget.enableUser=true
      - homepage.widget.showEpisodeNumber=true
    restart: unless-stopped
    networks:
      - media_net

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./config/jackett:/config
      - ./downloads:/downloads
    labels:
      - homepage.group=Indexers
      - homepage.name=Jackett
      - homepage.icon=jackett
      - homepage.href=http://localhost:9117
    restart: unless-stopped
    networks:
      - media_net

networks:
  media_net:
    external: true
