version: "3.8"
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - homepage.group=System
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=http://localhost:9000
    networks:
      - core_net
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.docker.localhost`)"
      - homepage.group=System
      - homepage.name=Whoami
      - homepage.icon=test
    networks:
      - core_net
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Runs at 4 AM daily
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
    labels:
      - homepage.group=System
      - homepage.name=Watchtower
      - homepage.icon=watchtower
    restart: unless-stopped
    networks:
      - core_net
      - media_net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.docker.localhost`)"
      - homepage.group=System
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.href=http://home.docker.localhost
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - core_net
      - media_net
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.docker.localhost`)"
      - homepage.group=System
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma
      - homepage.href=http://uptime.docker.localhost
    restart: unless-stopped
    networks:
      - core_net
      - media_net

  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    container_name: dockge
    ports:
      - 5001:5001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.docker.localhost`)"
      - homepage.group=System
      - homepage.name=Dockge
      - homepage.icon=docker
      - homepage.href=http://dockge.docker.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/rajesh/homelab:/home/rajesh/homelab
    environment:
      - DOCKGE_STACKS_DIR=/home/rajesh/homelab
    networks:
      - core_net
      - media_net

networks:
  core_net:
    name: core_net
  media_net:
    external: true
