version: "3.8"
services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - homepage.group=System
      - homepage.name=Traefik
      - homepage.icon=traefik
      - homepage.href=http://localhost:9000
    networks:
      - core_net
      - media_net
      - tools_net
    restart: unless-stopped

  whoami:
    image: traefik/whoami
    container_name: whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.home`)"
      - homepage.group=System
      - homepage.name=Whoami
      - homepage.icon=test
    networks:
      - core_net
      - media_net
      - tools_net
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=${TZ}
      - WATCHTOWER_SCHEDULE=0 0 4 * * * # Runs at 4 AM daily
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false
    labels:
      - homepage.group=System
      - homepage.name=Watchtower
      - homepage.icon=watchtower
    restart: unless-stopped
    networks:
      - core_net
      - media_net
      - tools_net

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homepage.rule=Host(`home.home`)"
      - homepage.group=System
      - homepage.name=Homepage
      - homepage.icon=homepage
      - homepage.href=http://home.home
    volumes:
      - ./config/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=192.168.0.88:3000
    networks:
      - core_net
      - media_net
      - tools_net
    restart: unless-stopped

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./data:/app/data
    ports:
      - 3001:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.home`)"
      - homepage.group=System
      - homepage.name=Uptime Kuma
      - homepage.icon=uptime-kuma
      - homepage.href=http://uptime.home
    restart: unless-stopped
    networks:
      - core_net
      - media_net
      - tools_net

  dockge:
    image: louislam/dockge:1
    restart: unless-stopped
    container_name: dockge
    ports:
      - 5001:5001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dockge.rule=Host(`dockge.home`)"
      - homepage.group=System
      - homepage.name=Dockge
      - homepage.icon=docker
      - homepage.href=http://dockge.home
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data
      - /home/rajesh/homelab:/home/rajesh/homelab
    environment:
      - DOCKGE_STACKS_DIR=/home/rajesh/homelab
    networks:
      - core_net
      - media_net
      - tools_net
  
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: '192.168.0.149'
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Asia/Kuala_Lumpur'
      WEBPASSWORD: 'correct horse battery staple'
      FTLCONF_dns_listeningMode: 'all'
      VIRTUAL_HOST: pi.hole
      PROXY_LOCATION: pi.hole
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    restart: unless-stopped

networks:
  pihole_network:
    driver: macvlan
    driver_opts:
      parent: enp2s0
    ipam:
      config:
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
          ip_range: 192.168.0.149/32
  core_net:
    name: core_net
  media_net:
    external: true
  tools_net:
    external: true
